// https://help.aliyun.com/document_detail/ess/api-document/api-use-notes.html
module.exports = [
  'CreateScalingGroup',
  'ModifyScalingGroup',
  'DescribeScalingGroups',
  'EnableScalingGroup',
  'DisableScalingGroup',
  'DeleteScalingGroup',
  'DescribeScalingInstances',
  'CreateScalingConfiguration',
  'DescribeScalingConfigurations',
  'DeleteScalingConfiguration',
  'CreateScalingRule',
  'ModifyScalingRule',
  'DescribeScalingRules',
  'DeleteScalingRule',
  'ExecuteScalingRule',
  'AttachInstances',
  'RemoveInstances',
  'CreateScheduledTask',
  'ModifyScheduledTask',
  'DescribeScheduledTasks',
  'DeleteScheduledTask',
  'DescribeScalingActivities'
];
